syntax = "proto3";
option java_multiple_files = true;
option java_package = "com.kuaia.common.raft";

enum CommandType {
  SAVE_TASK = 0;
  UPDATE_STATE = 1;
  SAVE_TASK_RECORD = 2;
  CAS_TASK_RECORD = 3;
}

message RaftCommand {
  CommandType type = 1;
  oneof payload {
    SaveTaskPayload save_task = 2;
    UpdateStatePayload update_state = 3;
    TaskRecordPayload task_record = 4;
  }
}

message SaveTaskPayload {
  string task_id = 1;
  bytes definition = 2; // Serialized TaskDefinition
}

message UpdateStatePayload {
  string task_id = 1;
  int32 state_code = 2;
}

message TaskRecordPayload {
  string task_id = 1;
  bytes record = 2;
  int64 expected_version = 3;
}
